# DEV environment setting#
#---------------------------
# Server Port
server:
  port: 8042
  
# Database ---------------- Postgres
spring:
  datasource:    
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/orderms    
    username: githubuser
    password: dbPass123
  #Hibernate
  jpa:
    #Hibernate
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
    show-sql: false
    
# Actuator allow all for dev
management:
  endpoints:
    web:
      exposure:
        include: "*"
    
# REST APIs
customer:
  rest:
    host: http://localhost:8041/customers/

restaurant:
  rest:
    host: http://localhost:8040/restaurants/