# DEV environment setting#
#---------------------------
  
# Database ---------------- Postgres
spring:
  datasource:    
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/restaurant    
    username: githubuser
    password: dbPass123
  #Hibernate
  jpa:
    #Hibernate
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
    show-sql: false
    
